"""Add timestamp columns

Revision ID: e68658c83984
Revises: e2412789c190
Create Date: 2024-08-17 14:00:00.000000

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "e68658c83984"
down_revision = "e2412789c190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timestamp columns to user table
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    
    # Add timestamp columns to item table
    op.add_column("item", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("item", sa.Column("updated_at", sa.DateTime(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE \"user\" SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE \"item\" SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove timestamp columns from item table
    op.drop_column("item", "updated_at")
    op.drop_column("item", "created_at")
    
    # Remove timestamp columns from user table
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###